# exec = export SLURP_ARGS='-d -c FFDAD4BB -b 673B3444 -s 00000000'

general {
	col.active_border = rgb(ffff00) rgb(ff8000) 45deg
    col.inactive_border = rgb(ffff00)
}
misc {
    background_color = rgba(1D1011FF)
}
plugin {
    hyprexpo {
        bg_col = rgb(ffff00)   # теж варто перенести сюди, щоб колір експо мінявся з темою
    }
}

windowrule {
  name = pin-gradient-border
  match:pin = 1
  border_color = rgba(ffff66cc) rgba(ffb84dcc) 45deg
  border_size = 1
}

