# ~/.config/hypr/hyprpaper.conf
# ipc = on


wallpaper {
    monitor = eDP-1
    path = /home/andriy4k/Pictures/wallpapers/forest-and-montain.jpg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/andriy4k/Pictures/wallpapers/forest-and-montain.jpg
    fit_mode = cover
}
