format = """\
$username$hostname\
$directory\
$git_branch\
$git_status\
\n$character"""


[username]
show_always = true
style_user = "bold green"
format = "[$user]($style)@"

[hostname]
ssh_only = false
format = "[$hostname](bold green) "
style = "bold green"

[directory]
style = "bold green"
format = "[$path]($style) "
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "green"
format = "[$symbol $branch]($style) "

[git_status]
style = "bold green"
format = "[$all_status$ahead_behind]($style) "

[time]
disabled = false
time_format = "%H:%M"
style = "dimmed green"
format = "[$time]($style) "

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "
